name: uEmacs

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'Formula/uemacs.rb'
      - '.github/workflows/uemacs.yml'
  pull_request:
    paths:
      - 'Formula/uemacs.rb'
      - '.github/workflows/uemacs.yml'
  schedule:
    - cron:  '0 6 * * *'

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        os: [macos-15]

    steps:
    - uses: actions/checkout@v5

    - name: Tap uEmacs
      run: |
        brew tap daviderestivo/uemacs

    - name: Build uEmacs
      run: |
        brew update
        brew upgrade || true
        brew install --verbose uemacs

    - name: Test uEmacs installation
      run: brew test uemacs
